// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUdTmpFLWXUvfhmoGIAXsmd3ovBLcRZac',
    appId: '1:230253675938:web:d582576fbfb76ab25f5efb',
    messagingSenderId: '230253675938',
    projectId: 'pblkelompok1-26c51',
    authDomain: 'pblkelompok1-26c51.firebaseapp.com',
    storageBucket: 'pblkelompok1-26c51.firebasestorage.app',
    measurementId: 'G-MCJY77MDPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7BpfZxybQz8fLyetmTXSJhBxhfLu1pZM',
    appId: '1:230253675938:android:dc22265096c7df9c5f5efb',
    messagingSenderId: '230253675938',
    projectId: 'pblkelompok1-26c51',
    storageBucket: 'pblkelompok1-26c51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcqLxOEQsQRcB40wpDMXgOuXl2isXW9MU',
    appId: '1:230253675938:ios:98859f6ee05a63515f5efb',
    messagingSenderId: '230253675938',
    projectId: 'pblkelompok1-26c51',
    storageBucket: 'pblkelompok1-26c51.firebasestorage.app',
    iosBundleId: 'com.example.mobileKel1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcqLxOEQsQRcB40wpDMXgOuXl2isXW9MU',
    appId: '1:230253675938:ios:98859f6ee05a63515f5efb',
    messagingSenderId: '230253675938',
    projectId: 'pblkelompok1-26c51',
    storageBucket: 'pblkelompok1-26c51.firebasestorage.app',
    iosBundleId: 'com.example.mobileKel1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUdTmpFLWXUvfhmoGIAXsmd3ovBLcRZac',
    appId: '1:230253675938:web:8e780462b9ec13d65f5efb',
    messagingSenderId: '230253675938',
    projectId: 'pblkelompok1-26c51',
    authDomain: 'pblkelompok1-26c51.firebaseapp.com',
    storageBucket: 'pblkelompok1-26c51.firebasestorage.app',
    measurementId: 'G-WNVPBBXJKN',
  );
}
